@ECHO OFF

ECHO CCGUIWidget.BAT:     Compiling GUI\Widget

CALL CC Button
CALL CC Checkbox
CALL CC Dialog
CALL CC Edit
CALL CC EditBin
CALL CC EditDec
CALL CC EditFloat
CALL CC EditHex
CALL CC Framewin
CALL CC GUI_EditBin
CALL CC GUI_EditDec
CALL CC GUI_EditFloat
CALL CC GUI_EditHex
CALL CC GUI_EditString
CALL CC Listbox
CALL CC Marquee
CALL CC Messagebox
CALL CC Progbar
CALL CC Radio
CALL CC Scrollbar
CALL CC Slider
CALL CC Terminal
CALL CC Text
CALL CC Widget
CALL CC Widget_3D
CALL CC Widget_None
CALL CC Widget_Simple
