function Hd = filter_IIR_Butter(Fs,N,Fc1,Fc2)
%FILTER_IIR_BUTTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
% Generated on: 30-Oct-2017 18:25:15

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.

%%%%%%%Fs = 1000;  % Sampling Frequency

%%%%%%%%N   = 8;   % Order
%%%%%%%%Fc1 = 4;   % First Cutoff Frequency
%%%%%%%%Fc2 = 15;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
