/*
  C-file generated by Bitmap converter for emWin GSC V2.30b, compiled May  8 2002, 10:05:14

  Copyright (C) 1998-2002
  Segger Microcontroller Systeme GmbH
  www.segger.com

  Solutions for real time microcontroller applications

  Source file: GUI_MouseArrow
  Dimensions:  11 * 18
  NumColors:   3
*/

#include <stdlib.h>

#include "GUI.H"

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

const GUI_COLOR ColorsGUI_MouseArrow[] = {
  0,0x000000,0xFFFFFF
};

const GUI_LOGPALETTE PalGUI_MouseArrow = {
  3,	/* number of entries */
  1, 	/* Has transparency */
  &ColorsGUI_MouseArrow[0]
};

const unsigned char acGUI_MouseArrow[] = {
  0x50, 0x00, 0x00,
  0x64, 0x00, 0x00,
  0x69, 0x00, 0x00,
  0x6A, 0x40, 0x00,
  0x6A, 0x90, 0x00,
  0x6A, 0xA4, 0x00,
  0x6A, 0xA9, 0x00,
  0x6A, 0xAA, 0x40,
  0x6A, 0xAA, 0x90,
  0x6A, 0xA5, 0x54,
  0x69, 0xA4, 0x00,
  0x64, 0x69, 0x00,
  0x50, 0x69, 0x00,
  0x40, 0x1A, 0x40,
  0x00, 0x1A, 0x40,
  0x00, 0x06, 0x90,
  0x00, 0x06, 0x90,
  0x00, 0x01, 0x40
};

const GUI_BITMAP GUI_MouseArrow = {
 11,                  /* XSize */
 18,                  /* YSize */
 3,                   /* BytesPerLine */
 2,                   /* BitsPerPixel */
 acGUI_MouseArrow,    /* Pointer to picture data (indices) */
 &PalGUI_MouseArrow   /* Pointer to palette */
};

/* *** End of file *** */
