function Hd = filter_butterLPF(Fs,N,Fc)
%FILTER_LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
% Generated on: 09-Nov-2017 21:00:59

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
%%%%%%%%%Fs = 10000;  % Sampling Frequency

%%%%%%%%%%N  = 10;   % Order
%%%%%%%%%%Fc = 100;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]
